INSERT INTO TRANSCODE(CODE) VALUES('CSC');
INSERT INTO TRANSCODE(CODE) VALUES('ASC');
INSERT INTO TRANSCODE(CODE) VALUES('CCL');
INSERT INTO TRANSCODE(CODE) VALUES('CC');

INSERT INTO EMPLOYEE(name, hrid) VALUES('John', '111');

